# Generated by Django 3.1 on 2020-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_xml', models.FileField(upload_to='', verbose_name='XML файл')),
                ('file_xslt', models.FileField(upload_to='', verbose_name='XSLT файл')),
            ],
            options={
                'verbose_name': 'XSLT Ковертер',
                'verbose_name_plural': 'XSLT Ковертер',
            },
        ),
    ]
