# Generated by Django 3.1 on 2020-08-08 17:57

import bank.utils.fields
import bank.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название карты')),
                ('owner', bank.utils.fields.CardOwnerField(max_length=200, validators=[bank.utils.validators.CardOwnerValidator], verbose_name='Владелец')),
                ('pan', bank.utils.fields.CardNumberField(max_length=16, validators=[bank.utils.validators.CardNumberValidator], verbose_name='Номер карты')),
                ('expired_date', bank.utils.fields.ValidThruField(max_length=10, validators=[bank.utils.validators.ValidThruValidator], verbose_name='Срок истечения')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Баланс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Карты',
                'verbose_name_plural': 'Карты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Сумма')),
                ('operation_type', models.CharField(choices=[('income', 'доход'), ('expense', 'расход')], max_length=50, verbose_name='Тип операции')),
                ('contr_agent', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контрагент')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-date'],
            },
        ),
    ]
