# Generated by Django 3.1 on 2020-08-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MD5Rainbow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=255, verbose_name='Хэш')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Хэши/ключи',
            },
        ),
    ]
